#!/usr/bin/env python3
'''Generate deterministic SeaORM and Diesel projections for Fiducia commercial intake.

The canonical DDL stays in fiducia-cloud/fiducia-infra. This script consumes the
reviewed normalized catalog snapshot checked into this compatibility repository
and emits ORM projection code only. It never emits or applies migrations.
'''

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "schema" / "commercial.catalog.json"
SEA_ORM_PATH = ROOT / "generated" / "commercial_sea_orm.rs"
DIESEL_PATH = ROOT / "generated" / "commercial_diesel.rs"
PROVENANCE_PATH = ROOT / "generated" / "commercial_provenance.rs"
LOCK_PATH = ROOT / "commercial-projection.lock.json"

SEA_TYPES = {
    "text": "String",
    "char(2)": "String",
    "char(3)": "String",
    "integer": "i32",
    "bigint": "i64",
    "boolean": "bool",
    "timestamptz": "DateTimeWithTimeZone",
    "jsonb": "Json",
    "numeric(24,6)": "Decimal",
}

DIESEL_SQL_TYPES = {
    "text": "Text",
    "char(2)": "Bpchar",
    "char(3)": "Bpchar",
    "integer": "Integer",
    "bigint": "BigInt",
    "boolean": "Bool",
    "timestamptz": "Timestamptz",
    "jsonb": "Jsonb",
    "numeric(24,6)": "Numeric",
}

DIESEL_RUST_TYPES = {
    "text": "String",
    "char(2)": "String",
    "char(3)": "String",
    "integer": "i32",
    "bigint": "i64",
    "boolean": "bool",
    "timestamptz": "chrono::DateTime<chrono::Utc>",
    "jsonb": "serde_json::Value",
    "numeric(24,6)": "bigdecimal::BigDecimal",
}

HEADER = "// @generated by tools/generate_commercial_projections.py; DO NOT EDIT.\n"


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def load_catalog() -> tuple[dict[str, Any], str]:
    text = CATALOG_PATH.read_text(encoding="utf-8")
    catalog = json.loads(text)
    if catalog.get("format") != "fiducia.orm-projection.v1":
        raise ValueError("unsupported commercial catalog format")
    if catalog.get("schema") != "fiducia_commercial":
        raise ValueError("commercial catalog must target fiducia_commercial")

    tables = catalog.get("tables")
    if not isinstance(tables, list) or not tables:
        raise ValueError("commercial catalog must define at least one table")

    seen_tables: set[str] = set()
    for table in tables:
        name = table.get("name")
        if not isinstance(name, str) or not name:
            raise ValueError("every table requires a name")
        if name in seen_tables:
            raise ValueError(f"duplicate table: {name}")
        seen_tables.add(name)

        columns = table.get("columns")
        primary_key = table.get("primary_key")
        if not isinstance(columns, list) or not columns:
            raise ValueError(f"{name}: columns must be a non-empty list")
        if not isinstance(primary_key, list) or not primary_key:
            raise ValueError(f"{name}: primary_key must be a non-empty list")

        seen_columns: set[str] = set()
        for column in columns:
            column_name = column.get("name")
            sql_type = column.get("sql_type")
            nullable = column.get("nullable")
            if not isinstance(column_name, str) or not column_name:
                raise ValueError(f"{name}: every column requires a name")
            if column_name in seen_columns:
                raise ValueError(f"{name}: duplicate column {column_name}")
            seen_columns.add(column_name)
            if sql_type not in SEA_TYPES:
                raise ValueError(f"{name}.{column_name}: unsupported SQL type {sql_type!r}")
            if not isinstance(nullable, bool):
                raise ValueError(f"{name}.{column_name}: nullable must be boolean")

        missing_pk = [column for column in primary_key if column not in seen_columns]
        if missing_pk:
            raise ValueError(f"{name}: primary key references missing columns {missing_pk}")

    return catalog, text


def rust_type(type_map: dict[str, str], column: dict[str, Any]) -> str:
    value = type_map[column["sql_type"]]
    return f"Option<{value}>" if column["nullable"] else value


def render_sea_orm(catalog: dict[str, Any]) -> str:
    lines = [
        HEADER.rstrip(),
        "//! SeaORM entity projections for the `fiducia_commercial` schema.",
        "//!",
        "//! These are generated compatibility types, not migration authority.",
        "",
    ]
    for table in catalog["tables"]:
        lines.extend(
            [
                f"pub mod {table['name']} {{",
                "    use sea_orm::entity::prelude::*;",
                "",
                "    #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]",
                f'    #[sea_orm(schema_name = "{catalog["schema"]}", table_name = "{table["name"]}")]',
                "    pub struct Model {",
            ]
        )
        primary_key = set(table["primary_key"])
        for column in table["columns"]:
            if column["name"] in primary_key:
                lines.append("        #[sea_orm(primary_key, auto_increment = false)]")
            lines.append(
                f"        pub {column['name']}: {rust_type(SEA_TYPES, column)},"
            )
        lines.extend(
            [
                "    }",
                "",
                "    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]",
                "    pub enum Relation {}",
                "",
                "    impl ActiveModelBehavior for ActiveModel {}",
                "}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def render_diesel(catalog: dict[str, Any]) -> str:
    lines = [
        HEADER.rstrip(),
        "//! Diesel schema and query models for the `fiducia_commercial` schema.",
        "//!",
        "//! Composite foreign keys, checks, indexes, RLS, and triggers remain",
        "//! authoritative in the canonical SQL and are intentionally not restated here.",
        "",
    ]

    schema = catalog["schema"]
    for table in catalog["tables"]:
        pk = ", ".join(table["primary_key"])
        lines.extend(
            [
                "diesel::table! {",
                f"    {schema}.{table['name']} ({pk}) {{",
            ]
        )
        for column in table["columns"]:
            sql_type = DIESEL_SQL_TYPES[column["sql_type"]]
            if column["nullable"]:
                sql_type = f"Nullable<{sql_type}>"
            lines.append(f"        {column['name']} -> {sql_type},")
        lines.extend(["    }", "}", ""])

    lines.extend(
        [
            "pub mod models {",
            "    //! Struct projections whose field order exactly matches the generated Diesel tables.",
            "",
        ]
    )
    for table in catalog["tables"]:
        pk = ", ".join(table["primary_key"])
        lines.extend(
            [
                "    #[derive(",
                "        Debug, Clone, PartialEq, diesel::Queryable, diesel::Selectable, diesel::Identifiable,",
                "    )]",
                f"    #[diesel(table_name = crate::generated::commercial_diesel::{schema}::{table['name']})]",
                f"    #[diesel(primary_key({pk}))]",
                "    #[diesel(check_for_backend(diesel::pg::Pg))]",
                f"    pub struct {table['rust_model']} {{",
            ]
        )
        for column in table["columns"]:
            lines.append(
                f"        pub {column['name']}: {rust_type(DIESEL_RUST_TYPES, column)},"
            )
        lines.extend(["    }", ""])
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_provenance(catalog: dict[str, Any], catalog_text: str) -> str:
    authority = catalog["authority"]
    tables = catalog["tables"]
    table_names = "\n".join(f'    "{table["name"]}",' for table in tables)
    column_count = sum(len(table["columns"]) for table in tables)
    return f'''{HEADER}//! Generated source and projection provenance.

pub const COMMERCIAL_SCHEMA: &str = "{catalog["schema"]}";
pub const COMMERCIAL_TABLE_COUNT: usize = {len(tables)};
pub const COMMERCIAL_COLUMN_COUNT: usize = {column_count};
pub const COMMERCIAL_CATALOG_SHA256: &str = "{sha256_text(catalog_text)}";
pub const COMMERCIAL_SQL_GIT_BLOB_SHA1: &str = "{authority["sql"]["git_blob_sha1"]}";
pub const COMMERCIAL_JSON_SCHEMA_GIT_BLOB_SHA1: &str =
    "{authority["wire_json_schema"]["git_blob_sha1"]}";
pub const COMMERCIAL_TYPESPEC_GIT_BLOB_SHA1: &str =
    "{authority["typespec"]["git_blob_sha1"]}";

pub const COMMERCIAL_TABLES: &[&str] = &[
{table_names}
];
'''


def render_lock(
    catalog: dict[str, Any],
    catalog_text: str,
    generator_text: str,
    generated: dict[Path, str],
) -> str:
    authority = catalog["authority"]
    output_hashes = {
        str(path.relative_to(ROOT)): sha256_text(content)
        for path, content in sorted(generated.items(), key=lambda item: str(item[0]))
    }
    lock = {
        "format": "fiducia.orm-projection-lock.v1",
        "authority_status": authority["status"],
        "planned_editable_repository": authority["planned_editable_repository"],
        "compatibility_repository": authority["compatibility_repository"],
        "sources": {
            "sql": authority["sql"],
            "wire_json_schema": authority["wire_json_schema"],
            "typespec": authority["typespec"],
        },
        "catalog": {
            "path": str(CATALOG_PATH.relative_to(ROOT)),
            "sha256": sha256_text(catalog_text),
            "table_count": len(catalog["tables"]),
            "column_count": sum(len(table["columns"]) for table in catalog["tables"]),
        },
        "generator": {
            "path": str(Path(__file__).resolve().relative_to(ROOT)),
            "sha256": sha256_text(generator_text),
        },
        "outputs": output_hashes,
        "policy": (
            "This lock describes generated compatibility projections only. "
            "Canonical SQL and live catalog verification remain migration authority; "
            "fiducia-lib-core becomes the editable projection authority when provisioned."
        ),
    }
    return json.dumps(lock, indent=2, sort_keys=True) + "\n"


def expected_outputs() -> dict[Path, str]:
    catalog, catalog_text = load_catalog()
    generated = {
        SEA_ORM_PATH: render_sea_orm(catalog),
        DIESEL_PATH: render_diesel(catalog),
        PROVENANCE_PATH: render_provenance(catalog, catalog_text),
    }
    generator_text = Path(__file__).read_text(encoding="utf-8")
    generated[LOCK_PATH] = render_lock(catalog, catalog_text, generator_text, generated)
    return generated


def check(outputs: dict[Path, str]) -> int:
    mismatches: list[str] = []
    for path, expected in outputs.items():
        if not path.exists():
            mismatches.append(f"missing: {path.relative_to(ROOT)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            mismatches.append(f"stale: {path.relative_to(ROOT)}")
    if mismatches:
        print("commercial projection check failed:", file=sys.stderr)
        for mismatch in mismatches:
            print(f"  - {mismatch}", file=sys.stderr)
        return 1
    print(f"commercial projections are current ({len(outputs)} generated files)")
    return 0


def write(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when checked-in generated files differ from the catalog",
    )
    args = parser.parse_args()
    outputs = expected_outputs()
    if args.check:
        return check(outputs)
    write(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
